Traceback (most recent call last):
  File "/home/luis/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/luis/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/luis/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/luis/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/luis/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/luis/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/luis/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/luis/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import Calculadora as cal

print(cal.sumar(2,2))
print(cal.restar(2,2))
print(cal.multiplicacion(2,2))
print(cal.division(2,2))
print(cal.potencia(2,2))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mCalculadora[39;00m [38;5;28;01mas[39;00m [38;5;21;01mcal[39;00m
[1;32m      3[0m [38;5;28mprint[39m(cal[38;5;241m.[39msumar([38;5;241m2[39m,[38;5;241m2[39m))
[1;32m      4[0m [38;5;28mprint[39m(cal[38;5;241m.[39mrestar([38;5;241m2[39m,[38;5;241m2[39m))

[0;31mModuleNotFoundError[0m: No module named 'Calculadora'
ModuleNotFoundError: No module named 'Calculadora'

